[2022-10-31 21:26:45,094] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.create_table 2022-10-31T21:26:43.732296+00:00 [queued]>
[2022-10-31 21:26:45,107] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: user_processing.create_table 2022-10-31T21:26:43.732296+00:00 [queued]>
[2022-10-31 21:26:45,108] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 21:26:45,108] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2022-10-31 21:26:45,108] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2022-10-31 21:26:45,116] {taskinstance.py:1063} INFO - Executing <Task(PostgresOperator): create_table> on 2022-10-31T21:26:43.732296+00:00
[2022-10-31 21:26:45,120] {standard_task_runner.py:52} INFO - Started process 151 to run task
[2022-10-31 21:26:45,123] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'user_processing', 'create_table', '2022-10-31T21:26:43.732296+00:00', '--job-id', '30', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp28cl04n3', '--error-file', '/tmp/tmp2bvlsgtx']
[2022-10-31 21:26:45,123] {standard_task_runner.py:77} INFO - Job 30: Subtask create_table
[2022-10-31 21:26:45,154] {logging_mixin.py:104} INFO - Running <TaskInstance: user_processing.create_table 2022-10-31T21:26:43.732296+00:00 [running]> on host 8311e947f87b
[2022-10-31 21:26:45,188] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=create_table
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T21:26:43.732296+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-31T21:26:43.732296+00:00
[2022-10-31 21:26:45,188] {postgres.py:69} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
            );
        
[2022-10-31 21:26:45,194] {base.py:74} INFO - Using connection to: id: postgres. Host: postgres, Port: 5432, Schema: , Login: airflow, Password: XXXXXXXX, extra: None
[2022-10-31 21:26:45,198] {dbapi.py:180} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS users (
            firstname TEXT NOT NULL,
            lastname TEXT NOT NULL,
            country TEXT NOT NULL,
            username TEXT NOT NULL,
            password TEXT NOT NULL,
            email TEXT NOT NULL
            );
        , parameters: None
[2022-10-31 21:26:45,198] {dbapi.py:186} INFO - Rows affected: -1
[2022-10-31 21:26:45,198] {postgres.py:73} INFO - NOTICE:  relation "users" already exists, skipping

[2022-10-31 21:26:45,206] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=create_table, execution_date=20221031T212643, start_date=20221031T212645, end_date=20221031T212645
[2022-10-31 21:26:45,222] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-10-31 21:26:45,254] {local_task_job.py:146} INFO - Task exited with return code 0
